apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
<<<<<<< HEAD
      storage: 2Gi
=======
      storage: 2Gi

>>>>>>> origin/master
