apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: najiabderraouf2/frontend:2
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
              protocol: TCP
    
