apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ingress-nginx
spec:
  selector:
    app: frontend 
  ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
  type: NodePort  
